name: image_downloader
channels:
  - defaults
  - conda-forge
  - anaconda
dependencies:
  - python=3.8.12
  - pip=23.1.2
  - python-dotenv=0.19.2
  - psycopg2=2.8.6
  - omegaconf=2.2.1
  - hydra-core=1.1.1
  - rich=10.11.0
  - requests=2.26.0
  - markupsafe=2.1.1
  - jupyter=1.0.0
  - pandas=1.5.3
  - pillow=9.4.0
  - selenium=4.9.1
  - pip:
    - streamlit==1.22.0
